### ISSUE TITLE
CKAN Harvest URL not clear when adding a new Harvest Source

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-registry#14]
This might be a bit of a usability problem when we turn the site over to RA users.  Not sure people are going to know what to enter in this field.  Can it be automatically filled in based on the Organization the harvest is under, and the input field removed?

**Comment by lukecampbell** [comment]
Unfortunately it's not that easy. Harvests are not 1:1 with CKAN harvests and organizations. For example AOOS has two harvests, unidata and AOOS. And at one point AOOS had SECOORA as well...

**Comment by lukecampbell** [comment]
You had requested a link to the CKAN harvest, and having it be manually edited was the best I could come up with.

**Comment by mwengren** [comment]
@lukecampbell I'm confused, because doesn't each harvest source from a particular Organization that goes into the Registry get merged into a single Organization WAF in here https://registry.ioos.us/waf/?  In other words, both of the source harvest WAFs for AOOS get merged here https://registry.ioos.us/waf/AOOS/, so wont' CKAN just be doing a single harvest from the merged AOOS WAF?

**Comment by lukecampbell** [comment]
That's incorrect. 

For Example,
https://registry.ioos.us/waf/Unidata/

![screen shot 2016-08-26 at 9 29 42 am](https://cloud.githubusercontent.com/assets/1155163/18006844/a55203c4-6b6f-11e6-87a1-36cffd825a47.png)

**Comment by lukecampbell** [comment]
In CKAN, Unidata is part of AOOS. In the registry Unidata is it's own organization.

**Comment by lukecampbell** [comment]
I'm thinking I could refactor the system so that orgs are 1:1 with CKAN orgs.
