### ISSUE TITLE
Add Data Source full URL to the chart panel

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-registry#19]
Doing some testing this morning, I noticed that the full WAF URL doesn't appear anywhere on the /harvests view.  The hostname appears in the table, but there will probably be several cases where RAs have multiple WAFs on the same host.  Could it be added below the title (eg NERACOOS WAF) on the chart panel?

**Comment by lukecampbell** [comment]
The links are active and work but I shortened the text so that the table is readable.

**Comment by lukecampbell** [comment]
If I use full URLs the table becomes unusable because it's too wide to fit on the screen. Another option would be to move the table full width and have the harvest stats below the table.

**Comment by lukecampbell** [comment]
![screen](https://cloud.githubusercontent.com/assets/1155163/18134236/bce004d2-6f6b-11e6-928a-b1a582d89b84.png)

**Comment by mwengren** [comment]
What I was talking about was putting the full URL in the chart panel when
you click on a data source in the table. Can you add another row above the
chart that shows the full URL below the WAF name?  I don't think the full
URL needs to be in the table, but you do need some way to show which WAF is
actually selected within that view, otherwise the only distinguishing
identifier is the name. Will lead to confusion for RAs with many WAFs I
expect.

**Comment by lukecampbell** [comment]
Yeah, no problem.
