### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-registry#8]
May be good idea to support HTTPS in the Registry UI.

**Comment by lukecampbell** [comment]
I would like HTTPS for every service on the entire internet. I'll try to get you a cost estimate for a certificate. Maybe I can get a domain cert for ioos.us.

**Comment by rsignell-usgs** [comment]
@lukecampbell, if I recall right, NOAA agrees with you, and is requiring https on all NOAA servers as of some date.  @mwengren, do you remember the date?

**Comment by mwengren** [comment]
Hmm, I'm not sure of a NOAA-specific date beyond the Federal requirement:

Agencies must make all existing websites and services accessible through a
secure connection [3] <https://https.cio.gov/#footnote-3> (HTTPS-only, with
HSTS) by December 31, 2016.

From: https://https.cio.gov/.

Soon enough regardless, although doubtful that will actually happen.

**Comment by rsignell-usgs** [comment]
@mwengren , yipes, I forgot/didn't know this was Federal government mandate.   We better get cracking on our websites!

**Comment by lukecampbell** [comment]
I don't know if this applies to services and websites hosted by contractors though. If it does, I would very much like to leverage this mandate to force all of our services to be upgraded to HTTPS. There's also huge performance improvements when using HTTPS.

https://www.troyhunt.com/i-wanna-go-fast-https-massive-speed-advantage/

Not to mention it brings legitimacy and obviously security to your sites.

**Comment by mwengren** [comment]
I think the requirement is only for .gov TLD sites, but I haven't read
through the policy.  I just look with a wary eye at any site with a login
over plain HTTP, so I think we should definitely buy a certificate for the
Registry if not a solution for all of the ioos.us sites.

**Comment by lukecampbell** [comment]
I completely agree.
